# -*- coding: utf-8 -*-
"""Jacomino_Rabadeux_Code_pour_pth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydsIAOIS7wHwQJ595dSk20ZJB6QSVpy_
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')
# Example of data loading from google drive:
# load an image, convert it as an array of float, and divide to have [0,1] values
# path to the image on the drive
image_filename = "/content/drive/MyDrive/Colab Notebooks/160068.jpg"

im = np.array(Image.open(image_filename), dtype=float)/255

# display the original images
plt.figure()
plt.imshow(im)
plt.show()

"""
CHARGER ET UTILISER UN MODÈLE PRÉ-ENTRAÎNÉ (.pth)

Ce code permet de :
1. Charger un fichier .pth (modèle entraîné)
2. Restaurer l'architecture DnCNN
3. Utiliser le modèle pour débruiter des images
"""

import torch
import torch.nn as nn
from torchvision import transforms
from torchvision.utils import make_grid
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
import os

# ==============================================================================
# ÉTAPE 1 : UPLOAD DU FICHIER .pth SUR COLAB
# ==============================================================================

print("="*70)
print("CHARGEMENT DU MODÈLE PRÉ-ENTRAÎNÉ")
print("="*70)

print("\n Upload depuis votre ordinateur")
print("   Exécutez la cellule ci-dessous pour uploader le fichier .pth")

from google.colab import files
uploaded = files.upload()
# Après exécution, un bouton apparaîtra pour sélectionner votre fichier .pth

# Récupérer le nom du fichier uploadé
if uploaded:
    pth_filename = list(uploaded.keys())[0]
    print(f" Fichier uploadé : {pth_filename}")
else:
    print("\n Charger depuis Google Drive")
    pth_filename = "/content/drive/MyDrive/Colab Notebooks/dncnn_sigma25_epoch50.pth"
    print(f"   Chemin : {pth_filename}")

# ==============================================================================
# ÉTAPE 2 : DÉFINIR L'ARCHITECTURE DnCNN (même que pour l'entraînement)
# ==============================================================================

class DnCNN(nn.Module):
    """Architecture DnCNN - DOIT être identique à celle utilisée pour l'entraînement"""

    def __init__(self, in_channels=1, out_channels=1, depth=17, n_filters=64):
        super(DnCNN, self).__init__()

        layers = []

        # Première couche
        layers.append(nn.Conv2d(in_channels, n_filters, kernel_size=3, padding=1, bias=True))
        layers.append(nn.ReLU(inplace=True))

        # Couches intermédiaires
        for _ in range(depth - 2):
            layers.append(nn.Conv2d(n_filters, n_filters, kernel_size=3, padding=1, bias=False))
            layers.append(nn.BatchNorm2d(n_filters))
            layers.append(nn.ReLU(inplace=True))

        # Dernière couche
        layers.append(nn.Conv2d(n_filters, out_channels, kernel_size=3, padding=1, bias=True))

        self.dncnn = nn.Sequential(*layers)

    def forward(self, x):
        return self.dncnn(x)

# ==============================================================================
# ÉTAPE 3 : CHARGER LE MODÈLE
# ==============================================================================

print("\n" + "="*70)
print("CHARGEMENT DES POIDS DU MODÈLE")
print("="*70)

# Déterminer le device (GPU si disponible)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"\n  Device : {device}")

# Créer l'architecture vide
model = DnCNN(in_channels=1, out_channels=1, depth=17, n_filters=64)

# Charger le fichier .pth
try:
    checkpoint = torch.load(pth_filename, map_location=device)
    print(f" Fichier .pth chargé avec succès !")

    # Afficher les clés disponibles dans le checkpoint
    print(f"\n Clés dans le checkpoint : {list(checkpoint.keys())}")

    # Cas 1 : Le checkpoint contient un dictionnaire avec 'model_state_dict'
    if 'model_state_dict' in checkpoint:
        model.load_state_dict(checkpoint['model_state_dict'])
        print(" Poids du modèle chargés depuis 'model_state_dict'")

        # Afficher des infos supplémentaires si disponibles
        if 'epoch' in checkpoint:
            print(f"   - Époque d'entraînement : {checkpoint['epoch']}")
        if 'noise_sigma' in checkpoint:
            print(f"   - Niveau de bruit d'entraînement : σ={checkpoint['noise_sigma']}")
        if 'test_psnrs' in checkpoint and len(checkpoint['test_psnrs']) > 0:
            print(f"   - PSNR final : {checkpoint['test_psnrs'][-1]:.2f} dB")

    # Cas 2 : Le checkpoint contient directement les poids (state_dict)
    elif 'dncnn.0.weight' in checkpoint or any('dncnn' in k for k in checkpoint.keys()):
        model.load_state_dict(checkpoint)
        print(" Poids du modèle chargés directement")

    # Cas 3 : Format inconnu
    else:
        print("Format du checkpoint non reconnu")
        print("   Contenu du checkpoint :")
        for key in checkpoint.keys():
            print(f"      - {key}: {type(checkpoint[key])}")

    # Mettre le modèle en mode évaluation
    model = model.to(device)
    model.eval()
    print(f"\n Modèle chargé et prêt à l'emploi (mode évaluation)")

except FileNotFoundError:
    print(f"ERREUR : Fichier {pth_filename} non trouvé")
    print("   Vérifiez le chemin ou uploadez le fichier")
except Exception as e:
    print(f"ERREUR lors du chargement : {e}")

# ==============================================================================
# ÉTAPE 4 : FONCTION DE DÉBRUITAGE
# ==============================================================================

def denoise_image(model, image_path, noise_sigma=25, device='cuda'):
    """
    Débruite une image en utilisant le modèle chargé.

    Args:
        model: Modèle DnCNN chargé
        image_path: Chemin vers l'image à débruiter
        noise_sigma: Niveau de bruit (0-255) - utilisé pour la normalisation
        device: 'cuda' ou 'cpu'

    Returns:
        dict contenant les images propre, bruitée, débruitée
    """
    # Charger l'image
    img = Image.open(image_path).convert('L')
    img_tensor = transforms.ToTensor()(img).unsqueeze(0)  # [1, 1, H, W]

    # Ajouter du bruit
    noise = torch.randn_like(img_tensor) * (noise_sigma / 255.0)
    noisy_img = img_tensor + noise
    noisy_img = torch.clamp(noisy_img, 0, 1)

    # Normalisation (μ=0, σ=1)
    mean = noisy_img.mean()
    std = noisy_img.std()
    noisy_normalized = (noisy_img - mean) / (std + 1e-8)

    # Déplacer sur le device
    noisy_normalized = noisy_normalized.to(device)

    # Prédire le bruit
    with torch.no_grad():
        noise_pred = model(noisy_normalized)

    # Débruiter
    denoised_normalized = noisy_normalized - noise_pred
    denoised = denoised_normalized * std + mean
    denoised = torch.clamp(denoised, 0, 1)

    # Calculer le PSNR
    mse = torch.mean((denoised - img_tensor.to(device)) ** 2)
    psnr = 20 * torch.log10(1.0 / torch.sqrt(mse))

    return {
        'clean': img_tensor.cpu(),
        'noisy': noisy_img.cpu(),
        'denoised': denoised.cpu(),
        'psnr': psnr.item()
    }


def denoise_from_noisy_image(model, noisy_image_path, device='cuda'):
    """
    Débruite une image DÉJÀ bruitée (image réelle ou déjà corrompue).

    Args:
        model: Modèle DnCNN chargé
        noisy_image_path: Chemin vers l'image déjà bruitée
        device: 'cuda' ou 'cpu'

    Returns:
        dict contenant l'image bruitée et débruitée
    """
    # Charger l'image bruitée
    noisy_img = Image.open(noisy_image_path).convert('L')
    noisy_tensor = transforms.ToTensor()(noisy_img).unsqueeze(0)  # [1, 1, H, W]

    # Normalisation (μ=0, σ=1)
    mean = noisy_tensor.mean()
    std = noisy_tensor.std()
    noisy_normalized = (noisy_tensor - mean) / (std + 1e-8)

    # Déplacer sur le device
    noisy_normalized = noisy_normalized.to(device)

    # Prédire le bruit
    with torch.no_grad():
        noise_pred = model(noisy_normalized)

    # Débruiter
    denoised_normalized = noisy_normalized - noise_pred
    denoised = denoised_normalized * std + mean
    denoised = torch.clamp(denoised, 0, 1)

    return {
        'noisy': noisy_tensor.cpu(),
        'denoised': denoised.cpu()
    }

# ==============================================================================
# ÉTAPE 5 : EXEMPLES D'UTILISATION
# ==============================================================================

print("\n" + "="*70)
print("EXEMPLES D'UTILISATION DU MODÈLE")
print("="*70)

# ===== EXEMPLE 1 : Débruiter une image propre (ajouter du bruit puis débruiter) =====
print("\n EXEMPLE 1 : Débruiter une image propre")
print("-" * 70)

# À ADAPTER : chemin vers une image de test
test_image_path = "/content/drive/MyDrive/Colab Notebooks/160068.jpg"  # MODIFIER

try:
    results = denoise_image(model, test_image_path, noise_sigma=25, device=device)

    print(f"Image débruitée avec succès !")
    print(f"   PSNR : {results['psnr']:.2f} dB")

    # Visualisation
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    axes[0].imshow(results['clean'].squeeze(), cmap='gray')
    axes[0].set_title('Image Propre', fontsize=12, fontweight='bold')
    axes[0].axis('off')

    axes[1].imshow(results['noisy'].squeeze(), cmap='gray')
    axes[1].set_title('Image Bruitée (σ=25)', fontsize=12, fontweight='bold')
    axes[1].axis('off')

    axes[2].imshow(results['denoised'].squeeze(), cmap='gray')
    axes[2].set_title(f'Image Débruitée\nPSNR: {results["psnr"]:.2f} dB',
                     fontsize=12, fontweight='bold', color='green')
    axes[2].axis('off')

    plt.tight_layout()
    plt.savefig('resultat_debruitage.png', dpi=150, bbox_inches='tight')
    plt.show()

except FileNotFoundError:
    print(f"Fichier {test_image_path} non trouvé")
    print("Uploadez une image ou modifiez le chemin")


# ==============================================================================
# INFORMATIONS SUR LE MODÈLE CHARGÉ
# ==============================================================================

print("\n" + "="*70)
print("INFORMATIONS SUR LE MODÈLE")
print("="*70)

# Compter les paramètres
total_params = sum(p.numel() for p in model.parameters())
print(f"Nombre de paramètres : {total_params:,}")
print(f"Device : {next(model.parameters()).device}")
print(f"Mode : {'Évaluation' if not model.training else 'Entraînement'}")

# Si le checkpoint contient des métadonnées
if 'checkpoint' in locals():
    print(f"\n Métadonnées du checkpoint :")
    for key, value in checkpoint.items():
        if key not in ['model_state_dict', 'optimizer_state_dict']:
            print(f"   - {key}: {value}")

print("\n" + "="*70)
print("MODÈLE CHARGÉ ET PRÊT À L'UTILISATION")

# ===== EXEMPLE : Débruiter une image aléatoire du dataset BSD68 =====
print("\n" + "-" * 70)
print("EXEMPLE : Débruiter une image aléatoire de BSD68")
print("-" * 70)

import random
import os

# Dossier contenant les images BSD68
bsd68_folder = "/content/drive/MyDrive/Colab Notebooks/originalBSD68"

try:
    # Récupérer toutes les images du dossier
    image_list = glob.glob(os.path.join(bsd68_folder, "*.jpg"))
    image_list += glob.glob(os.path.join(bsd68_folder, "*.png"))

    if len(image_list) == 0:
        print(f" Aucune image trouvée dans {bsd68_folder}")
    else:
        # Sélectionner une image aléatoire
        random_image_path = random.choice(image_list)
        image_name = os.path.basename(random_image_path)

        # Choisir un sigma aléatoire entre 10 et 50
        random_sigma = random.randint(10, 15)

        print(f" Image sélectionnée : {image_name}")
        print(f" Niveau de bruit : σ = {random_sigma}")

        # Charger l'image propre
        clean_img = Image.open(random_image_path).convert('L')
        clean_tensor = transforms.ToTensor()(clean_img).unsqueeze(0)  # [1, 1, H, W]

        # Ajouter du bruit avec le sigma aléatoire
        noise = torch.randn_like(clean_tensor) * (random_sigma / 255.0)
        noisy_tensor = clean_tensor + noise
        noisy_tensor = torch.clamp(noisy_tensor, 0, 1)

        # Normalisation pour le modèle (μ=0, σ=1)
        mean = noisy_tensor.mean()
        std = noisy_tensor.std()
        noisy_normalized = (noisy_tensor - mean) / (std + 1e-8)

        # Déplacer sur le device et débruiter
        noisy_normalized = noisy_normalized.to(device)

        with torch.no_grad():
            noise_pred = model(noisy_normalized)

        # Reconstruction de l'image débruitée
        denoised_normalized = noisy_normalized - noise_pred
        denoised = denoised_normalized * std + mean
        denoised = torch.clamp(denoised, 0, 1)

        # Calculer le PSNR
        mse = torch.mean((denoised.cpu() - clean_tensor) ** 2)
        psnr = 20 * torch.log10(1.0 / torch.sqrt(mse))

        print(f" Image débruitée avec succès !")
        print(f"   PSNR : {psnr.item():.2f} dB")

        # Visualisation comparative
        fig, axes = plt.subplots(1, 3, figsize=(18, 6))

        axes[0].imshow(clean_tensor.squeeze(), cmap='gray')
        axes[0].set_title(f'Image Propre\n({image_name})', fontsize=12, fontweight='bold')
        axes[0].axis('off')

        axes[1].imshow(noisy_tensor.squeeze(), cmap='gray')
        axes[1].set_title(f'Image Bruitée\nσ = {random_sigma}',
                         fontsize=12, fontweight='bold', color='red')
        axes[1].axis('off')

        axes[2].imshow(denoised.cpu().squeeze(), cmap='gray')
        axes[2].set_title(f'Image Débruitée\nPSNR: {psnr.item():.2f} dB',
                         fontsize=12, fontweight='bold', color='green')
        axes[2].axis('off')

        plt.tight_layout()
        plt.savefig(f'debruitage_sigma{random_sigma}.png', dpi=150, bbox_inches='tight')
        print(f" Figure sauvegardée : debruitage_sigma{random_sigma}.png")
        plt.show()

        # Afficher un zoom pour mieux voir les détails
        print("\n Zoom sur une région pour mieux voir les détails :")

        # Extraire une région d'intérêt (centre de l'image)
        h, w = clean_tensor.shape[2], clean_tensor.shape[3]
        crop_size = min(100, h//2, w//2)
        y_start, x_start = h//2 - crop_size//2, w//2 - crop_size//2

        clean_crop = clean_tensor[:, :, y_start:y_start+crop_size, x_start:x_start+crop_size]
        noisy_crop = noisy_tensor[:, :, y_start:y_start+crop_size, x_start:x_start+crop_size]
        denoised_crop = denoised.cpu()[:, :, y_start:y_start+crop_size, x_start:x_start+crop_size]

        fig, axes = plt.subplots(1, 3, figsize=(18, 6))

        axes[0].imshow(clean_crop.squeeze(), cmap='gray')
        axes[0].set_title('Propre (zoom)', fontsize=12, fontweight='bold')
        axes[0].axis('off')

        axes[1].imshow(noisy_crop.squeeze(), cmap='gray')
        axes[1].set_title(f'Bruitée σ={random_sigma} (zoom)', fontsize=12, fontweight='bold')
        axes[1].axis('off')

        axes[2].imshow(denoised_crop.squeeze(), cmap='gray')
        axes[2].set_title(f'Débruitée (zoom)', fontsize=12, fontweight='bold')
        axes[2].axis('off')

        plt.tight_layout()
        plt.savefig(f'debruitage_sigma{random_sigma}_zoom.png', dpi=150, bbox_inches='tight')
        plt.show()

except FileNotFoundError:
    print(f" Dossier {bsd68_folder} non trouvé")
    print("  Vérifiez le chemin et assurez-vous que Google Drive est monté")
