# -*- coding: utf-8 -*-
"""DnCNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZRWdnDn1bMnUD3CtxHAaTwLHg_HvF6e
"""

# Projet Débruitage par Deep Learning - DnCNN
# Basé sur l'article "Beyond a Gaussian Denoiser: Residual Learning of Deep CNN for Image Denoising"

# ==============================================================================
# INSTALLATION ET IMPORTS
# ==============================================================================

# Colab only - download and install PyTorch
#!pip install torch torchvision

import numpy as np
from PIL import Image
from IPython.display import clear_output
import matplotlib.pyplot as plt
from torch.utils.data import Dataset
from torchvision import transforms
from torchvision.utils import make_grid
import glob
import os
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
import math

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')
# Example of data loading from google drive:
# load an image, convert it as an array of float, and divide to have [0,1] values
# path to the image on the drive
image_filename = "/content/drive/MyDrive/Colab Notebooks/160068.jpg"

im = np.array(Image.open(image_filename), dtype=float)/255

# display the original images
plt.figure()
plt.imshow(im)
plt.show()

# ==============================================================================
# 1. CALCUL DES STATISTIQUES GLOBALES (NORMALISATION)
# ==============================================================================

def compute_global_stats(image_folder, pattern="*.jpg", max_images=None):
    """
    Calcule la moyenne et l'écart-type GLOBAL sur toute la base d'images.

    Args:
        image_folder: dossier contenant les images
        pattern: motif pour glob
        max_images: nombre max d'images à analyser (None = toutes)

    Returns:
        mean_global: moyenne globale (scalaire pour grayscale)
        std_global: écart-type global (scalaire pour grayscale)
    """
    print("\n" + "="*60)
    print("CALCUL DES STATISTIQUES GLOBALES")
    print("="*60)

    image_list = sorted(glob.glob(os.path.join(image_folder, pattern)))

    if max_images is not None:
        image_list = image_list[:max_images]

    print(f"Nombre d'images à analyser: {len(image_list)}")

    # Accumulateurs pour calcul en une passe
    sum_pixels = 0.0
    sum_squares = 0.0
    n_pixels = 0

    for img_path in tqdm(image_list, desc="Calcul statistiques"):
        # Charge l'image
        img = Image.open(img_path)

        # Convertit en grayscale (méthode standard)
        if img.mode != 'L':
            img = img.convert('L')

        # Convertit en array [0, 1]
        img_array = np.array(img, dtype=np.float32) / 255.0

        # Accumule
        sum_pixels += img_array.sum()
        sum_squares += (img_array ** 2).sum()
        n_pixels += img_array.size

    # Calcul moyenne et écart-type
    mean_global = sum_pixels / n_pixels
    variance_global = (sum_squares / n_pixels) - (mean_global ** 2)
    std_global = np.sqrt(variance_global)

    print(f"\n✓ Statistiques globales calculées:")
    print(f"  Moyenne: {mean_global:.4f}")
    print(f"  Écart-type: {std_global:.4f}")
    print(f"  Pixels analysés: {n_pixels:,}")

    return mean_global, std_global

# ==============================================================================
# 2. DATASET AVEC NORMALISATION GLOBALE (CORRIGÉ)
# ==============================================================================

class DenoisingDataset(Dataset):
    """
    Dataset pour DnCNN avec normalisation GLOBALE.

    IMPORTANT:
    - La normalisation utilise les statistiques GLOBALES (mean_global, std_global)
    - Le bruit est ajouté APRÈS normalisation
    - Retourne (noisy_normalized, noise_normalized)
    """

    def __init__(self, root_dir, pattern="*.jpg", patch_size=40,
                 noise_sigma=25, mean_global=0.0, std_global=1.0,
                 patches_per_image=100):
        """
        Args:
            root_dir: dossier contenant les images
            pattern: motif pour glob
            patch_size: taille des patches
            noise_sigma: niveau de bruit (0-255)
            mean_global: moyenne globale calculée sur toute la base
            std_global: écart-type global calculé sur toute la base
            patches_per_image: nombre de patches extraits par image
        """
        self.list_im = sorted(glob.glob(os.path.join(root_dir, pattern)))
        self.patch_size = patch_size
        self.noise_sigma = noise_sigma / 255.0  # Normalisation en [0, 1]
        self.mean_global = mean_global
        self.std_global = std_global
        self.patches_per_image = patches_per_image

        print(f"\n✓ Dataset initialisé:")
        print(f"  Images: {len(self.list_im)}")
        print(f"  Patches par image: {patches_per_image}")
        print(f"  Total patches: {len(self)}")
        print(f"  Patch size: {patch_size}×{patch_size}")
        print(f"  Noise σ: {noise_sigma}")
        print(f"  Normalisation: μ={mean_global:.4f}, σ={std_global:.4f}")

    def __len__(self):
        return len(self.list_im) * self.patches_per_image

    def __getitem__(self, idx):
        # Sélectionne une image (avec répétition)
        img_idx = idx // self.patches_per_image
        img_path = self.list_im[img_idx]

        # Charge l'image
        img = Image.open(img_path)

        # Convertit en grayscale (méthode PIL standard)
        if img.mode != 'L':
            img = img.convert('L')

        # Convertit en array [0, 1]
        img_array = np.array(img, dtype=np.float32) / 255.0

        # Extrait un patch aléatoire
        h, w = img_array.shape

        # Assure que l'image est assez grande
        if h < self.patch_size or w < self.patch_size:
            # Resize si nécessaire
            new_h = max(h, self.patch_size)
            new_w = max(w, self.patch_size)
            img = img.resize((new_w, new_h), Image.BILINEAR)
            img_array = np.array(img, dtype=np.float32) / 255.0
            h, w = img_array.shape

        # Position aléatoire
        top = np.random.randint(0, h - self.patch_size + 1)
        left = np.random.randint(0, w - self.patch_size + 1)

        # Extrait le patch PROPRE [0, 1]
        clean_patch = img_array[top:top+self.patch_size,
                                left:left+self.patch_size].copy()

        # ========================================
        # ÉTAPE 1: NORMALISATION GLOBALE
        # ========================================
        clean_normalized = (clean_patch - self.mean_global) / self.std_global

        # ========================================
        # ÉTAPE 2: AJOUT DU BRUIT (sur données normalisées)
        # ========================================
        # Le bruit doit aussi être normalisé par std_global
        noise_normalized = np.random.randn(*clean_normalized.shape).astype(np.float32) * (self.noise_sigma / self.std_global)

        # Image bruitée normalisée
        noisy_normalized = clean_normalized + noise_normalized

        # Convertit en tenseurs [1, H, W]
        clean_normalized = torch.from_numpy(clean_normalized).unsqueeze(0)
        noisy_normalized = torch.from_numpy(noisy_normalized).float().unsqueeze(0)
        noise_normalized = torch.from_numpy(noise_normalized).float().unsqueeze(0)

        # Pour évaluation: garde aussi les versions originales [0, 1]
        clean_original = torch.from_numpy(clean_patch).unsqueeze(0)

        return {
            'noisy': noisy_normalized,        # Entrée du réseau
            'noise': noise_normalized,        # Target du réseau
            'clean_original': clean_original, # Pour calcul PSNR
        }

# ==============================================================================
# 3. ARCHITECTURE DnCNN (corrigé)
# ==============================================================================

class DnCNN(nn.Module):
    """
    DnCNN Network pour le débruitage d'images.
    Architecture basée sur Zhang et al. 2017
    """

    def __init__(self, in_channels=1, out_channels=1, depth=17, n_filters=64):
        """
        Args:
            in_channels: nombre de canaux d'entrée (1 pour grayscale)
            out_channels: nombre de canaux de sortie (1 pour grayscale)
            depth: profondeur du réseau (17 pour DnCNN-S)
            n_filters: nombre de filtres (64 dans l'article)
        """
        super(DnCNN, self).__init__()

        self.depth = depth
        layers = []

        # Première couche: Conv + ReLU (PAS de BatchNorm)
        layers.append(nn.Conv2d(in_channels, n_filters,
                               kernel_size=3, padding=1, bias=True))
        layers.append(nn.ReLU(inplace=True))

        # Couches intermédiaires: Conv + BN + ReLU
        for _ in range(depth - 2):
            layers.append(nn.Conv2d(n_filters, n_filters,
                                   kernel_size=3, padding=1, bias=False))
            layers.append(nn.BatchNorm2d(n_filters))
            layers.append(nn.ReLU(inplace=True))

        # Dernière couche: Conv seulement
        layers.append(nn.Conv2d(n_filters, out_channels,
                               kernel_size=3, padding=1, bias=True))

        self.dncnn = nn.Sequential(*layers)

        # Initialisation des poids (He initialization)
        self._initialize_weights()

    def _initialize_weights(self):
        """Initialise les poids selon He et al."""
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        """
        Forward pass.
        Args:
            x: image bruitée normalisée
        Returns:
            bruit prédit (normalisé)
        """
        return self.dncnn(x)

# ==============================================================================
# 4. FONCTIONS UTILITAIRES (corrigé)
# ==============================================================================

def denormalize(tensor_normalized, mean_global, std_global):
    """
    Dénormalise un tensor.

    Args:
        tensor_normalized: tensor normalisé
        mean_global: moyenne globale utilisée pour la normalisation
        std_global: écart-type global

    Returns:
        tensor dénormalisé dans [0, 1]
    """
    return tensor_normalized * std_global + mean_global


def compute_psnr(img1, img2):
    """
    Calcule le PSNR entre deux images.

    Args:
        img1, img2: tensors [B, C, H, W] avec valeurs en [0, 1]

    Returns:
        PSNR moyen sur le batch (dB)
    """
    mse = F.mse_loss(img1, img2, reduction='mean')
    if mse == 0:
        return float('inf')
    return 20 * torch.log10(torch.tensor(1.0)) - 10 * torch.log10(mse)


def visualize_results(model, dataloader, device, mean_global, std_global, num_samples=4):
    """
    Visualise les résultats de débruitage.
    """
    model.eval()

    # Récupère un batch
    batch = next(iter(dataloader))

    with torch.no_grad():
        noisy = batch['noisy'][:num_samples].to(device)
        clean_original = batch['clean_original'][:num_samples]

        # Prédiction du bruit (normalisé)
        noise_pred = model(noisy)

        # Image débruitée (normalisée)
        denoised_normalized = noisy - noise_pred

        # Dénormalisation
        denoised = denormalize(denoised_normalized.cpu(), mean_global, std_global)
        denoised = torch.clamp(denoised, 0, 1)

        # Dénormalise aussi noisy pour affichage
        noisy_denorm = denormalize(noisy.cpu(), mean_global, std_global)
        noisy_denorm = torch.clamp(noisy_denorm, 0, 1)

    # Calcul PSNR
    psnr = compute_psnr(denoised, clean_original)

    # Affichage
    fig, axes = plt.subplots(3, num_samples, figsize=(16, 10))

    for i in range(num_samples):
        # Image propre
        axes[0, i].imshow(clean_original[i, 0].cpu().numpy(), cmap='gray', vmin=0, vmax=1)
        axes[0, i].set_title(f'Propre {i+1}')
        axes[0, i].axis('off')

        # Image bruitée
        axes[1, i].imshow(noisy_denorm[i, 0].cpu().numpy(), cmap='gray', vmin=0, vmax=1)
        axes[1, i].set_title(f'Bruitée {i+1}')
        axes[1, i].axis('off')

        # Image débruitée
        axes[2, i].imshow(denoised[i, 0].cpu().numpy(), cmap='gray', vmin=0, vmax=1)
        axes[2, i].set_title(f'Débruitée {i+1}')
        axes[2, i].axis('off')

    plt.suptitle(f'Résultats de débruitage - PSNR moyen: {psnr:.2f} dB',
                 fontsize=14, y=0.98)
    plt.tight_layout()
    plt.show()

    return psnr.item()

# ==============================================================================
# 5. ENTRAÎNEMENT (corrigé)
# ==============================================================================

def train_epoch(model, dataloader, optimizer, device, mean_global, std_global):
    """Entraîne le modèle sur une époque."""
    model.train()
    total_loss = 0
    total_psnr = 0

    pbar = tqdm(dataloader, desc="Training")
    for batch in pbar:
        # Données normalisées
        noisy = batch['noisy'].to(device)
        noise_target = batch['noise'].to(device)
        clean_original = batch['clean_original'].to(device)

        # Forward
        optimizer.zero_grad()
        noise_pred = model(noisy)

        # Loss: MSE sur le bruit (normalisé)
        loss = F.mse_loss(noise_pred, noise_target)

        # Backward
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        # Calcul PSNR (sur images dénormalisées)
        with torch.no_grad():
            denoised_norm = noisy - noise_pred
            denoised = denormalize(denoised_norm, mean_global, std_global)
            denoised = torch.clamp(denoised, 0, 1)
            psnr = compute_psnr(denoised, clean_original)
            total_psnr += psnr.item()

        pbar.set_postfix({'loss': f'{loss.item():.4f}', 'psnr': f'{psnr.item():.2f}'})

    return total_loss / len(dataloader), total_psnr / len(dataloader)


def evaluate(model, dataloader, device, mean_global, std_global):
    """Évalue le modèle."""
    model.eval()
    total_loss = 0
    total_psnr = 0

    with torch.no_grad():
        for batch in tqdm(dataloader, desc="Evaluating"):
            noisy = batch['noisy'].to(device)
            noise_target = batch['noise'].to(device)
            clean_original = batch['clean_original'].to(device)

            # Prédiction
            noise_pred = model(noisy)

            # Loss
            loss = F.mse_loss(noise_pred, noise_target)
            total_loss += loss.item()

            # PSNR
            denoised_norm = noisy - noise_pred
            denoised = denormalize(denoised_norm, mean_global, std_global)
            denoised = torch.clamp(denoised, 0, 1)
            psnr = compute_psnr(denoised, clean_original)
            total_psnr += psnr.item()

    return total_loss / len(dataloader), total_psnr / len(dataloader)

# ==============================================================================
# 6. SCRIPT PRINCIPAL (corrigé)
# ==============================================================================

if __name__ == "__main__":

    # ========================================
    # PARAMÈTRES
    # ========================================
    DATA_FOLDER = "/content/drive/MyDrive/Colab Notebooks/originalBSD68/"
    NOISE_SIGMA = 25     # Niveau de bruit
    PATCH_SIZE = 40      # Taille des patches
    BATCH_SIZE = 128     # Taille du batch
    DEPTH = 17           # Profondeur DnCNN-S
    N_EPOCHS = 50        # Nombre d'époques
    PATCHES_PER_IMAGE = 100  # Patches extraits par image

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Device: {device}")

    # ========================================
    # ÉTAPE 1: CALCUL STATISTIQUES GLOBALES
    # ========================================
    mean_global, std_global = compute_global_stats(
        DATA_FOLDER,
        pattern="*.jpg",  # ADAPTE SELON TES FICHIERS
        max_images=None   # Toutes les images
    )

    # ========================================
    # ÉTAPE 2: CRÉATION DU DATASET
    # ========================================
    full_dataset = DenoisingDataset(
        root_dir=DATA_FOLDER,
        pattern="*.jpg",
        patch_size=PATCH_SIZE,
        noise_sigma=NOISE_SIGMA,
        mean_global=mean_global,
        std_global=std_global,
        patches_per_image=PATCHES_PER_IMAGE
    )

    # Après la création du dataset
    if len(full_dataset) == 0:
        raise ValueError(f"Aucune image trouvée dans {DATA_FOLDER} avec le motif *.jpg. Vérifiez le format des fichiers.")

    # Split train/val/test
    train_size = int(0.7 * len(full_dataset))
    val_size = int(0.15 * len(full_dataset))
    test_size = len(full_dataset) - train_size - val_size

    dataset_train, dataset_val, dataset_test = torch.utils.data.random_split(
        full_dataset,
        [train_size, val_size, test_size],
        generator=torch.Generator().manual_seed(42)
    )

    print(f"\nSplit: Train={train_size}, Val={val_size}, Test={test_size}")

    # Dataloaders
    dataloader_train = torch.utils.data.DataLoader(
        dataset_train, batch_size=BATCH_SIZE, shuffle=True,
        num_workers=2, pin_memory=True
    )

    dataloader_val = torch.utils.data.DataLoader(
        dataset_val, batch_size=BATCH_SIZE, shuffle=False,
        num_workers=2, pin_memory=True
    )

    dataloader_test = torch.utils.data.DataLoader(
        dataset_test, batch_size=BATCH_SIZE, shuffle=False,
        num_workers=2, pin_memory=True
    )

    # ========================================
    # ÉTAPE 3: CRÉATION DU MODÈLE
    # ========================================
    model = DnCNN(in_channels=1, out_channels=1, depth=DEPTH, n_filters=64)
    model = model.to(device)

    n_params = sum(p.numel() for p in model.parameters())
    print(f"\nNombre de paramètres: {n_params:,}")

    # Optimizer
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)

    # Scheduler
    scheduler = torch.optim.lr_scheduler.MultiStepLR(
        optimizer, milestones=[30, 45], gamma=0.1
    )

    # ========================================
    # ÉTAPE 4: ENTRAÎNEMENT
    # ========================================
    print("\n" + "="*60)
    print("DÉBUT DE L'ENTRAÎNEMENT")
    print("="*60)

    train_losses = []
    val_losses = []
    train_psnrs = []
    val_psnrs = []

    best_psnr = 0

    for epoch in range(N_EPOCHS):
        print(f"\n{'='*60}")
        print(f"Époque {epoch+1}/{N_EPOCHS} - LR: {optimizer.param_groups[0]['lr']:.2e}")
        print(f"{'='*60}")

        # Entraînement
        train_loss, train_psnr = train_epoch(
            model, dataloader_train, optimizer, device, mean_global, std_global
        )
        train_losses.append(train_loss)
        train_psnrs.append(train_psnr)

        # Validation
        val_loss, val_psnr = evaluate(
            model, dataloader_val, device, mean_global, std_global
        )
        val_losses.append(val_loss)
        val_psnrs.append(val_psnr)

        print(f"\nTrain - Loss: {train_loss:.6f}, PSNR: {train_psnr:.2f} dB")
        print(f"Val   - Loss: {val_loss:.6f}, PSNR: {val_psnr:.2f} dB")

        # Sauvegarde du meilleur modèle
        if val_psnr > best_psnr:
            best_psnr = val_psnr
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'val_psnr': val_psnr,
                'mean_global': mean_global,
                'std_global': std_global,
            }, f'best_dncnn_sigma{NOISE_SIGMA}.pth')
            print(f"✓ Meilleur modèle sauvegardé (PSNR: {best_psnr:.2f} dB)")

        # Update LR
        scheduler.step()

        # Visualisation périodique
        if (epoch + 1) % 10 == 0:
            visualize_results(model, dataloader_val, device, mean_global, std_global)

    # ========================================
    # ÉTAPE 5: ÉVALUATION FINALE
    # ========================================
    print("\n" + "="*60)
    print("ÉVALUATION FINALE SUR TEST SET")
    print("="*60)

    test_loss, test_psnr = evaluate(
        model, dataloader_test, device, mean_global, std_global
    )

    print(f"Test Loss: {test_loss:.6f}")
    print(f"Test PSNR: {test_psnr:.2f} dB")

    # Visualisation finale
    visualize_results(model, dataloader_test, device, mean_global, std_global, num_samples=8)

    # ========================================
    # ÉTAPE 6: COURBES D'APPRENTISSAGE
    # ========================================
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    axes[0].plot(train_losses, label='Train', linewidth=2)
    axes[0].plot(val_losses, label='Val', linewidth=2)
    axes[0].set_xlabel('Époque', fontsize=12)
    axes[0].set_ylabel('Loss (MSE)', fontsize=12)
    axes[0].set_title('Évolution de la Loss', fontsize=14)
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    axes[1].plot(train_psnrs, label='Train', linewidth=2, color='green')
    axes[1].plot(val_psnrs, label='Val', linewidth=2, color='orange')
    axes[1].set_xlabel('Époque', fontsize=12)
    axes[1].set_ylabel('PSNR (dB)', fontsize=12)
    axes[1].set_title('Évolution du PSNR', fontsize=14)
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

    print("\n✓ Entraînement terminé !")

# ==============================================================================
# SAUVEGARDE DU MODÈLE
# ==============================================================================

# Sauvegarder le modèle entraîné
torch.save({
    'epoch': N_EPOCHS,
    'model_state_dict': net.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
    'train_losses': train_losses,
    'test_losses': test_losses,
    'test_psnrs': test_psnrs,
    'noise_sigma': NOISE_SIGMA,
    'patch_size': PATCH_SIZE
}, f'dncnn_sigma{NOISE_SIGMA}_epoch{N_EPOCHS}.pth')

print(f"\nModèle sauvegardé: dncnn_sigma{NOISE_SIGMA}_epoch{N_EPOCHS}.pth")
